#ifndef GREENTEA_LIBDNN_VERSION_HPP_
#define GREENTEA_LIBDNN_VERSION_HPP_

#define GREENTEA_LIBDNN_MAJOR 0
#define GREENTEA_LIBDNN_MINOR 1
#define GREENTEA_LIBDNN_PATCH 0


#endif  // GREENTEA_LIBDNN_VERSION_HPP_
